color = ''
project-name = 'default'

[default]
account_id = 'acct_1RwOpc2Ns4lIdnjx'
device_name = 'cfae5bc909ef'
display_name = 'Área restrita de New business'
test_mode_api_key = 'sk_test_51RwOpc2Ns4lIdnjxi8lwkhoBVikt3nYxiDH7uzAlf5hOAEcJU5ivxjKiKLLo1sHYMuOtd2PFkYMdOAnjYbC3DrJU00r18XFozZ'
test_mode_key_expires_at = '2025-11-16'
test_mode_pub_key = 'pk_test_51RwOpc2Ns4lIdnjxvbpyaArxgFHq2FZ6GyBJWUaX10wiErKo4CvLscRHLhtFAbEFvr7IE3PoUgUoii21lUtSjKMX00H365daDy'
