name: Monitor pending payments

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch: {}

concurrency:
  group: monitor-pending-payments
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call monitor endpoint
        shell: bash
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_TOKEN: ${{ secrets.CRON_TOKEN }}
        run: |
          set -e
          URL="${APP_URL}/api/monitor-pending-payments"
          for i in 1 2 3; do
            echo "Attempt $i: $URL"
            code=$(curl -s -o /dev/null -w "%{http_code}" -H "x-cron-token: ${CRON_TOKEN}" "$URL" || echo "000")
            if [ "$code" -ge 200 ] && [ "$code" -lt 300 ]; then
              echo "Success ($code)"
              exit 0
            fi
            echo "HTTP $code, retrying..."
            sleep 10
          done
          echo "Failed after retries"
          exit 1
